
TARGET_ARCH := arm
TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := mt6795
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_VARIANT := cortex-a7
TARGET_CPU_SMP := true
ARCH_ARM_HAVE_TLS_REGISTER := true
TARGET_BOOTLOADER_BOARD_NAME := m85
TARGET_NO_RADIOIMAGE := true

# module config
BOARD_USES_GENERIC_AUDIO := true
USE_CAMERA_STUB := true
DISABLE_DEXPREOPT := true
BOARD_USE_LEGACY_TOUCHSCREEN := true

# config_partition_size
BOARD_BOOTIMAGE_PARTITION_SIZE := 109312
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 142080
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 1310720
BOARD_USERDATAIMAGE_PARTITION_SIZE := 5324800
BOARD_FLASH_BLOCK_SIZE := 131072

# Kernel
BOARD_KERNEL_CMDLINE := bootopt=64S3,32N2,64N2
BOARD_KERNEL_PAGESIZE := 2048
BOARD_KERNEL_BASE = 0x40078000
TARGET_PREBUILT_KERNEL := device/meizu/mx5/kernel
BOARD_KERNEL_PAGESIZE := 2048
BOARD_MKBOOTIMG_ARGS := --ramdisk_offset 0x03f88000 --tags_offset 0x0df88000 --dt device/meizu/mx5/dt.img
KERNEL_EXFAT_MODULE_NAME := "exfat"
BOARD_DT_SIZE := 0
BOARD_SECOND_SIZE := 0
BOARD_SECOND_OFFSET := 00e88000

# Recovery
TARGET_RECOVERY_FSTAB := device/meizu/mx5/recovery.fstab
RECOVERY_FSTAB_VERSION := 2
RECOVERY_USE_VIRTUAL_KEY := true
BOARD_HAS_NO_SELECT_BUTTON := true\

# Assert
TARGET_OTA_ASSERT_DEVICE := mx5,m85

#TWRP (TWRP flags)
RECOVERY_SDCARD_ON_DATA := true
TW_NO_REBOOT_BOOTLOADER := true
DEVICE_RESOLUTION := 1080x1920