# mt6795 platform boardconfig
LOCAL_PATH := device/meizu/mx5
-include vendor/meizu/mx5/BoardConfigVendor.mk

# CPU
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 := 
TARGET_CPU_VARIANT := generic
TARGET_CPU_SMP := true

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv7-a-neon
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := cortex-a53
TARGET_BOARD_SUFFIX := _64

TARGET_CPU_CORTEX_A53 := true
TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := mt6795
ARCH_ARM_HAVE_TLS_REGISTER := true
TARGET_BOOTLOADER_BOARD_NAME := m85
TARGET_NO_RADIOIMAGE := true

# MTK Hardware
BOARD_HAS_MTK_HARDWARE := true
MTK_HARDWARE := true
BOARD_USES_LEGACY_MTK_AV_BLOB := true
COMMON_GLOBAL_CFLAGS += -DMTK_HARDWARE -DADD_LEGACY_ACQUIRE_BUFFER_SYMBOL
COMMON_GLOBAL_CPPFLAGS += -DMTK_HARDWARE
BOARD_CONNECTIVITY_VENDOR := MediaTek
BOARD_USES_MTK_AUDIO := true

# module config
BOARD_USES_GENERIC_AUDIO := true
USE_CAMERA_STUB := true
DISABLE_DEXPREOPT := true
BOARD_HAS_NO_SELECT_BUTTON := true

# Charger
BOARD_CHARGER_SHOW_PERCENTAGE := true

TARGET_SYSTEM_PROP := $(LOCAL_PATH)/system.prop

# PREBUILT_Chromium
PRODUCT_PREBUILT_WEBVIEWCHROMIUM := yes

# Bluetooth
BOARD_HAVE_BLUETOOTH := true
BOARD_HAVE_BLUETOOTH_MTK := true
BOARD_BLUETOOTH_DOES_NOT_USE_RFKILL := true
BOARD_BLUETOOTH_BDROID_BUILDCFG_INCLUDE_DIR := $(LOCAL_PATH)/bluetooth

# GPS
BOARD_GPS_LIBRARIES :=true
BOARD_CONNECTIVITY_MODULE := MT6630 
BOARD_MEDIATEK_USES_GPS := true

# FM
MTK_FM_SUPPORT :=false
MTK_FM_RX_SUPPORT :=false

# memory
TARGET_USE_CUSTOM_LUN_FILE_PATH := /sys/class/android_usb/android0/f_mass_storage/lun/file

# Display
USE_OPENGL_RENDERER := true
BOARD_EGL_CFG := $(LOCAL_PATH)/configs/egl.cfg
TARGET_SCREEN_HEIGHT := 1920
TARGET_SCREEN_WIDTH := 1080

# config_partition_size
BOARD_BOOTIMAGE_PARTITION_SIZE := 16777216
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 20971520
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 1610613000
BOARD_USERDATAIMAGE_PARTITION_SIZE := 28524940000
BOARD_FLASH_BLOCK_SIZE := 131072

# Kernel
TARGET_USES_64_BIT_BINDER := true
TARGET_IS_64_BIT := true
BOARD_KERNEL_CMDLINE := bootopt=64S3,32N2,64N2
BOARD_KERNEL_BASE := 0x40078000
TARGET_PREBUILT_KERNEL := device/meizu/mx5/kernel
BOARD_KERNEL_PAGESIZE := 2048
BOARD_MKBOOTIMG_ARGS := --base 0x40078000 --pagesize 2048 --kernel_offset 0x00008000 --ramdisk_offset 0x03f88000 --second_offset 0x00e88000 --tags_offset 0x0df88000
KERNEL_EXFAT_MODULE_NAME := "exfat"

# Recovery
TARGET_RECOVERY_FSTAB := device/meizu/mx5/configs/recovery.fstab
RECOVERY_FSTAB_VERSION := 2
RECOVERY_USE_VIRTUAL_KEY := true
BOARD_HAS_NO_SELECT_BUTTON := true
TARGET_RECOVERY_PIXEL_FORMAT := "RGBA_8888"

# Assert
TARGET_OTA_ASSERT_DEVICE := mx5,m85

#TWRP (TWRP flags)
RECOVERY_SDCARD_ON_DATA := true
TW_NO_REBOOT_BOOTLOADER := true
DEVICE_RESOLUTION := 1080x1920
